services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ozan
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"    # Host 5432 -> Container 5432
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      mynet:
        ipv4_address: 172.28.0.4

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"  # Host 27017 -> Container 27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      mynet:
        ipv4_address: 172.28.0.5

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
